### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by vrmorgue** [hamler-lang/hamler#129]
👋🏻
Where I can find the hamler formula on homebrew-core or cask repo's?

```
$ brew search hamler
No formula or cask found for "hamler".
```

The formula from the repository below is valid?
https://github.com/hamler-lang/homebrew-hamler

**Comment by emqplus** [comment]
@zhanghongtong pls check the issue. BTW, we plan to tag 0.1 and upgrade brew tomorrow:) @vrmorgue

**Comment by zhanghongtong** [comment]
Hi, @vrmorgue 
You need to execute `brew tap hamler-lang/hamler` before installing hamler

**Comment by vrmorgue** [comment]
@zhanghongtong
Yes, indeed, but the `README.md` doesn't contain any information about the brew tap.

**Comment by zhanghongtong** [comment]
@vrmorgue 
I'm sure [`README.md`](https://github.com/hamler-lang/homebrew-hamler/blob/master/README.md) contains relevant content, probably because it's not obvious enough.
