### ISSUE TITLE
Docs for Linux?

### ISSUE THREAD

**Issue by vegabook** [hamler-lang/hamler#155]
I love Erlang and agree with most of the motivations for the BEAM VM in the docs intro. The idea of strongly typed ML-style language on BEAM will most certainly build traction. However the Mac-only instructions, for both installation and source build, are a deterrent. Is there a Linux option?

**Comment by emqplus** [comment]
@vegabook coming soon... the linux install packages and docs will be released in 0.2.

**Comment by zhanghongtong** [comment]
Hi, @vegabook 
You can get the installation package through our [release page](https://github.com/hamler-lang/hamler/releases/tag/0.1.2) and install it on Linux. For how to install Hamler on Linux, you can check the PR: https://github.com/hamler-lang/hamler/pull/193
