### ISSUE TITLE
`hamler test` does not work

### ISSUE THREAD

**Issue by llaisdy** [hamler-lang/hamler#422]
Running `hamler test` straight after `hamler init` gets a cryptic error message:

```
$ hamler init
Generating src/Main.hm...
Generating Makefile...
$ ls
Makefile        ebin/            src/             test/
$ hamler test
hamler: /path/to/demo-project/lib: getDirectoryContents:openDirStream: does not exist (No such file or directory)
```

Does `hamler test` work?

I could really use an erlang with a strong type system.

Thanks

**Comment by EMQ-YangM** [comment]
I newly added the hamler test command available to users. #424
The previous test command can only be used by developers.

**Comment by llaisdy** [comment]
Thanks very much!  I'll try it out soon.

**Comment by EMQ-YangM** [comment]
[We released a new version. This may help you.](https://github.com/hamler-lang/hamler/releases/tag/0.2.2)

**Comment by llaisdy** [comment]
Will take it for a spin this weekend!

**Comment by llaisdy** [comment]
Working now, many thanks!
