### ISSUE TITLE
How to import `sum`? ... `mod`? etc

### ISSUE THREAD

**Issue by llaisdy** [hamler-lang/hamler#430]
Is there something wrong with my set up?

```
$ hamler repl
Hamler REPL, version 0.2.2
Type :? for help

> xs = range 0 9
> xs
[0,1,2,3,4,5,6,7,8,9]
> sum xs
Error found:
in module $REPL
at :1:1 - 1:4 (line 1, column 1 - line 1, column 4)

  Unknown value sum


or to contribute content related to this error.
```

I get similar error with eg `9 mod 2`.

Same error in the repl and in a module.
Same error if I `import {Prelude, Data.Foldable, ...}`.

1. Is something wrong with my set up (Hamler 0.2.2 from brew)?
2. How do I find which module has a function?

Keen to start using Hamler properly, even if it is not complete.

**Comment by llaisdy** [comment]
nb I can defined `sum`, but I'd like to know how to find & import library functions.

```
> sum = foldl (+) 0
> sum xs
45
```

**Comment by goldimax** [comment]
#428 for sum
we will add mod soon

**Comment by EMQ-YangM** [comment]
@laisdy We have added Project Layout in README.md. This might help you.

**Comment by llaisdy** [comment]
@EMQ-YangM  Thanks - very helpful

@EMQ-YangM @emqplus @goldimax si, very much a work-in-progress?  I've been using the release from homebrew, but it might be better if I cloned this repo and compiled from source?

**Comment by llaisdy** [comment]
Actually, `mod` (modulo) in erlang is `rem`, which you have:

```
> import Data.Ring
> rem 9 2
1
> 9 `rem` 2
1
```
