### ISSUE TITLE
Unknown value return

### ISSUE THREAD

**Issue by rolandtritsch** [hamler-lang/hamler#460]
Hi All. Quick question/heads up ... seems something is broken. If I try to compile `hamler-demo` with `hamler 0.4` it fails with ...
```
  in module Demo.Event
  at src/Demo/Event.hm:45:3 - 45:9 (line 45, column 3 - line 45, column 9)

    Unknown value return
```
I am about to give a demo/presentation on hamler. Can this be fixed by Wednesday?

**Comment by niltok** [comment]
`return` is removed in hamler 0.3
please use `pure` instead

**Comment by rolandtritsch** [comment]
Thanks. I will do a PR to fix `hamler-demo`.
